### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by raihan71**
Using logo Vonage in README.md file that makes looks nicer now

<strong>Before</strong>
image

<strong>After</strong>
image

### CODE REVIEW

**Comment by raihan71** [comment]
hi @mheap this is my first PR let me know what u think, thanks

**Comment by mheap** [comment]
Hey @raihan71, I'm going to hand this over to @bencgreenberg who's the maintainer of this project

**Comment by raihan71** [comment]
> Hey @raihan71, I'm going to hand this over to @bencgreenberg who's the maintainer of this project

Ohh ok cool

**Comment by bencgreenberg** [comment]
Hey @raihan71, Is there any other contributions you would like to make to the Rack middleware project? I'm going to have to decline this PR as it's not really adding much to the overall project. I'd be very happy to entertain another PR that had some more substantive contribution to it, either code or documentation! Looking forward to it.

**Comment by raihan71** [comment]
> Hey @raihan71, Is there any other contributions you would like to make to the Rack middleware project? I'm going to have to decline this PR as it's not really adding much to the overall project. I'd be very happy to entertain another PR that had some more substantive contribution to it, either code or documentation! Looking forward to it.

Aa I see it's alright

**Pull request closed without merging**
